//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `cardb.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cardb;

/** @hidden */
public class _CarPrxI extends com.zeroc.Ice._ObjectPrxI implements CarPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
