services:
    payment:
        image: payment:dev
        ports:
            - "5070:5070"
        volumes:
            - ./config/docker:/config
        depends_on:
            - "payments_db"
    payments_db:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: payments
