services:
    auth:
        image: auth:dev
        ports:
            - '5010:5010/tcp'
            - '5012:5012'
        volumes:
            - ./auth/Auth/config:/config
        networks:
            - car-rent
            - auth-db-connection
        depends_on:
             - 'auth_db'
    auth_db:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: auth
        networks:
            - auth-db-connection

    cars:
        image: cars:dev
        ports:
            - '5030:5030/tcp'
        volumes:
            - ./carDB/config/docker:/config
        networks:
            - car-rent
            - cars-db-connection
        depends_on:
             - 'cars_db'
             - 'blockchain'
    cars_db:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: cars
        networks:
            - cars-db-connection

    blockchain:
        image: trufflesuite/ganache-cli:latest
        ports:
            - '5000:8545'
        command: '--mnemonic "frog coin ten lottery sport awful broken extra call stereo police manual"'
        networks:
            - car-rent
networks:
    car-rent:
    auth-db-connection:
    cars-db-connection:
