services:
    auth:
        image: auth:dev
        ports:
            - "5010:5010/tcp"
            - "5012:5012"
        volumes:
            - ./Auth/config:/config
        networks:
            - car-rent
            - default
        depends_on:
             - "auth_db"
    auth_db:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: password
        networks:
            - default
networks:
    car-rent:
        external: true
