services:
    cars:
        image: cars:dev
        ports:
            - "5030:5030"
            - "5032:5032"
        volumes:
            - ./config/docker:/config
        depends_on:
             - "cars_db"
    cars_db:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: cars
