services:
    cars:
        image: cars:dev
        ports:
            - "5030:5030/tcp"
        volumes:
            - ./config/docker:/config
        networks:
            - car-rent
            - default
        depends_on:
             - "cars_db"
    cars_db:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: cars
        networks:
            - default
networks:
    car-rent:
        external: true
