# directories
**/.gradle/
**/.idea/

# files
Dockerfile*
**/*.md

# Compiled class file
*.class

# Log file
*.log

# BlueJ files
*.ctxt

# Package Files #
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar
