export const AUTH_SERVICE = "http://localhost:5010/api"
export const RENTAL_SERVICE = "http://localhost:5020/api"
export const CAR_DB_SERVICE = "http://localhost:5030/api"
export const TARRIF_SERVICE = "http://localhost:5040/api"
export const PAYMENT_SERVICE = "http://localhost:5070/api"
export const API_KEY = "AIzaSyDBaon-UCow_f01aVenTsvTjrNXiOrR6wQ"
