//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.8
//
// <auto-generated>
//
// Generated from file `auth.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Auth;

/** @hidden */
public class _AccountPrxI extends com.zeroc.Ice._ObjectPrxI implements AccountPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
