name: auth

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-auth:

    runs-on: ubuntu-latest

    steps:
    - name: Install ice key
      run: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv B6391CB2CFBA643D
    - name: Install ice repository
      run: sudo apt-add-repository -s "deb http://zeroc.com/download/Ice/3.7/ubuntu`lsb_release -rs` stable main"
    - name: Update package list
      run: sudo apt-get update
    - name: Install ice
      run: apt-get install zeroc-ice-all-runtime zeroc-ice-all-dev
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./auth
      run: dotnet restore
    - name: Build
      working-directory: ./auth
      run: dotnet build --no-restore
    - name: Run database container
      run: docker run -d -p 5011:5432 --name auth -e POSTGRES_PASSWORD=password postgres
    - name: Test
      working-directory: ./auth
      run: dotnet test --no-build --verbosity normal
