# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: carDB

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-carDB:

    runs-on: ubuntu-latest

    steps:
    - name: Install ice key
      run: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv B6391CB2CFBA643D
    - name: Install ice repository
      run: sudo apt-add-repository -s "deb http://zeroc.com/download/Ice/3.7/ubuntu`lsb_release -rs` stable main"
    - name: Update package list
      run: sudo apt-get update
    - name: Install ice
      run: sudo apt-get install zeroc-ice-all-runtime zeroc-ice-all-dev
    - uses: actions/checkout@v2
    - name: Set up JDK 18
      uses: actions/setup-java@v2
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Make gradlew executable
      run: chmod +x ./carDB/gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
        build-root-directory: carDB
